# render.yaml

services:
  - type: web
    name: zenyzoo-backend
    env: python
    region: oregon         # adjust to your region
    branch: main           # or your default branch
    plan: free          # or your chosen plan
    buildCommand: pip install -r requirements.txt
    releaseCommand: |
      python manage.py migrate --no-input
      python manage.py seed_cards
      python manage.py seed_player_cards
      python manage.py collectstatic --no-input
    startCommand: daphne zenyzoo.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: SECRET_KEY
        fromSecret: SECRET_KEY   # store in Render secrets
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "zenyzoo-backend.onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://zenyzoo-backend.onrender.com"
