# migrate, seed, collect static, then launch Daphne
python manage.py migrate --no-input
python manage.py seed_cards
python manage.py seed_player_cards
python manage.py collectstatic --no-input
daphne zenyzoo.asgi:application
