# Generated by Django 5.2.3 on 2025-06-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='in_battle_deck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='deck/'),
        ),
    ]
