# Generated by Django 5.2.3 on 2025-06-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_match_player_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bot_strategy',
            field=models.CharField(choices=[('random', 'Random')], default='random', max_length=32),
        ),
    ]
