# Generated by Django 5.2.3 on 2025-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_bot_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='credits',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
