# Generated by Django 5.2.3 on 2025-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_shopcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
