# Generated by Django 5.2.3 on 2025-07-13 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_card_price_player_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
